extends:
  [
    'eslint:recommended',
    'plugin:jest/recommended',
    'plugin:@typescript-eslint/recommended',
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
    'plugin:functional/external-recommended',
    'plugin:functional/recommended',
  ]
plugins: ['@typescript-eslint', 'jest', 'prettier', 'unused-imports', 'functional']
env:
  browser: false
  es6: true
  node: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: 'tsconfig.json'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
    - avoidEscape: true
      allowTemplateLiterals: true
  semi:
    - error
    - never
  object-curly-spacing:
    - warn
    - always
  '@typescript-eslint/explicit-function-return-type':
    - off
  '@typescript-eslint/camelcase':
    - off
  'no-useless-escape':
    - off
  '@typescript-eslint/no-non-null-assertion':
    - off
  '@typescript-eslint/no-unused-vars': 'off'
  unused-imports/no-unused-imports-ts: error
  unused-imports/no-unused-vars-ts:
    - warn
    - vars: all
      varsIgnorePattern: '^_'
      args: after-used
      argsIgnorePattern: '^_'
  functional/functional-parameters: 'off'
  functional/no-conditional-statement:
    - error
    - allowReturningBranches: 'ifExhaustive'
  functional/no-expression-statement:
    - error
    - ignorePattern: 't.*'
