remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  'boilerplate on GitHub':
    - 'https://github.com/gcanti/boilerplate'
